<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="WorkbookDb.fs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\create_excel_db.sql" Link="create_excel_db.sql" LogicalName="ExcelWorkbookDb.create_excel_db.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Stub.System.Data.SQLite.Core.NetStandard" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.401" />
  </ItemGroup>
</Project>
