<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="NameOpsTest.fs" />
        <Compile Include="WorksheetOpsTest.fs" />
        <Compile Include="PruneTest.fs" />
        <Compile Include="WorkbookDbTest.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.xUnit" Version="1.4.1" />
        <PackageReference Include="xunit.v3.mtp-v2" Version="4.0.1" />
        <PackageReference Update="FSharp.Core" Version="10.1.302" />

    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ExcelNumericalMethods\ExcelNumericalMethods.fsproj" />
        <ProjectReference Include="..\ExcelWorkbookDb\ExcelWorkbookDb.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="10.1.401" />
    </ItemGroup>

</Project>
